### ISSUE TITLE
Unhandled Promise Rejection when closing Session or Client

### ISSUE THREAD

**Issue by basedwon** [nknorg/ncp-js#14]
Getting this error: `UnhandledPromiseRejectionWarning: SessionClosedError: session closed` when trying to close the Client or Session instance. It looks like you need to wrap this section in a try/catch and bubble the error up rather than console.log it. That was someone can but a try/catch around the close method. Or you could return a promise rejection.

https://github.com/nknorg/ncp-js/blob/bc01300c2790686578bd4cec3059b75f566e3441/src/session.js#L662

https://github.com/nknorg/ncp-js/blob/bc01300c2790686578bd4cec3059b75f566e3441/src/session.js#L665

**Comment by yilunzhang** [comment]
`session closed` means you get `SessionClosedError`, which you will only get by calling `read`, `write`, `receiveWith`. Did you check your read and write call?

The code you linked will never return error, not to mention `SessionClosedError`.

**Comment by basedwon** [comment]
Also, I don't know what the actual error is because it's an unhandled rejection. I believe that changing the `close` method to this will at least then expose the error.

```js
class Session {
  async close() {
    this.readContext.cancel();
    this.writeContext.cancel();

    let timeout = new Channel();
    if (this.config.linger > 0) {
      setTimeout(timeout.close, this.config.linger);
    }

    try {
      if (this.config.linger !== 0) {
        await this._flushSendBuffer();

        await (async () => {
          try {
            while (true) {
              let interval = util.timeoutChan(100);
              switch (await Channel.select([interval.shift(), timeout.shift()])) {
                case interval:
                  if (this.sendWindowStartSeq === this.sendWindowEndSeq) {
                    return;
                  }
                  break;
                case timeout:
                  return;
              }
            }
          } catch (e) {
            throw e
          }
        })();
      }
      await this._sendClosePacket()
    } catch (e) {
      throw e
    }

    this.context.cancel();
    this.isClosed = true;
  }
}
```

**Comment by yilunzhang** [comment]
> Also, I don't know what the actual error is because it's an unhandled rejection.

It's SessionClosedError based on your log. See my comments above. Your changes shouldn't help as there shouldn't be any part in close method that will give you unhandled promise rejection.

**Comment by basedwon** [comment]
The code I linked is where the stack trace was pointing me. I'm building a test that opens a session, reads and writes some messages from both clients and then closes the clients. It works in normal mode (without session). I realize that if you throw the errors, it could break the process rather than just log the error. So perhaps you could log that final error only and that way we could at least see where the error is coming from.

**Comment by basedwon** [comment]
Whenever you do a loop involving an await and don't wrap the loop in a try/catch block, it will throw unhandled promise rejection. You could just wrap the loop in a try block but I'm actually getting 4 errors logged and they're all pretty much the same error.

**Comment by yilunzhang** [comment]
Is this the error message you see?
`UnhandledPromiseRejectionWarning: SessionClosedError: session closed`
It explicitly says `SessionClosedError`, which is only thrown in a few places as you can see by a global search, but not in close method.

> Whenever you do a loop involving an await and don't wrap the loop in a try/catch block, it will throw unhandled promise rejection. You could just wrap the loop in a try block but I'm actually getting 4 errors logged and they're all pretty much the same error.

Only if the await promise will ever reject. In this case Channel.select will never reject by its design.

**Comment by basedwon** [comment]
Here's the error 
`UnhandledPromiseRejectionWarning: SessionClosedError: session closed
    at Session.read (/Users/.../node_modules/@nkn/ncp/lib/session.js:673:15)`
 
Sorry, I should have included that initially

**Comment by basedwon** [comment]
And that's right inside of that loop, which is why I thought that initially. Perhaps it's still trying to read after the session is closed?

**Comment by yilunzhang** [comment]
This is code that throws the error as pointed by the log: `https://github.com/nknorg/ncp-js/blob/master/lib/session.js#L673` (note that it's pointing to /lib/ rather than /src/). It's the session.read method instead of close (the log also says that directly `session closed at Session.read`).

So I assume you are not catching session.read call?

**Comment by basedwon** [comment]
Ah yes, lib not src. And also yes, I was doing an async loop without a try/catch block. 
Perhaps I should follow my own advice, huh. : )

So, nevermind, you were right. Thank you much 👍
